### ISSUE TITLE
Defender flagging swars.exe - 2023-12-24

### ISSUE THREAD

**Issue by DaleCulpin** [swfans/swars#109]
![swars-defender-flag](https://github.com/swfans/swars/assets/18394298/63150769-bb18-4f43-8959-7fa85434a24f)

Not sure if this is an issue for anyone else, but Windows 11 Defender is flagging the EXE as a threat.

**Comment by mefistotelis** [comment]
Yeah, Microsoft must've defunded their anti-virus team. On previous update, `SearchIndexer.exe` was recognized as the same trojan.

It is true in some approach - Windows is a trojan welded into our society by ignorance of politicians, which gladly accepted it in schools. If Linux was being taught there, more people would have deep understanding of computers - Windows by design discourages learning of how OSes work.

Anyway, this is the problem which should be file to Microsoft and solved by Microsoft. No action will be taken on our side.

**Comment by Moburma** [comment]
Yes, I constantly get this, it's just Microsoft being silly. Find the executable in the Defender window and select to allow it and it will shut up. Happens most with the installer.

**Comment by DaleCulpin** [comment]
Understood. Cheers.
