### ISSUE TITLE
Interface button wrongly positioned after Mortal Game

### ISSUE THREAD

**Issue by geist22** [swfans/swars#120]
![options](https://github.com/swfans/swars/assets/107389189/889cfedf-5690-4b0d-8bb8-ba162e5c857c)

1. Load savegame
2. Start new Mortal Game
3. Logout
4. Load another savegame (regular, not mortal)

**Comment by mefistotelis** [comment]
Should be fixed with:
[swars: Smarter computing of system menu buttons positions](https://github.com/swfans/swars/commit/ac9363d2f08d7f7221d9476b557d39f39e159bff)

**Comment by geist22** [comment]
I'm getting this now with the following procedure:

1. Load savegame
2. Load mortal game
3. Logout
4. Load mortal game again

![01](https://github.com/swfans/swars/assets/107389189/92b56bf5-7d70-4a13-acad-c26d97a56b52)

**Comment by mefistotelis** [comment]
What about now?
[swars: Named a flag, fixed order of disabling buttons](https://github.com/swfans/swars/commit/d916da89616e7e07505a51bf98d0eade85314582)

The handling of GUI elements in the game is prone to errors - each screen has a separate drawing function, which draws items on screen one by one.

Typically in todays software there's an abstraction added, so that each screen adds components to "active" list and then there is one draw function which just redraws all components from that active list.

**Comment by geist22** [comment]
> The handling of GUI elements in the game is prone to errors

I couldn't get any of these issues to show in the original game, it's probably unique to the port.

> What about now?

I can't get the problem to appear anymore, so we can assume it's fixed now.
