### ISSUE TITLE
Item dupe: Dropping weapons you don't have

### ISSUE THREAD

**Issue by geist22** [swfans/swars#192]
Since we don't already have an issue about this, I thought I'd open one myself before it gets forgotten. Original game issue, found by rafalyp73 as explained in a comment on https://www.youtube.com/watch?v=S8QY-dNRQQ8.

Agents can be made to drop items they don't have.

To reproduce:
1. Agent 1 has an Uzi, agent 2 has a Minigun
2. Click left or right (doesn't matter) on agent 1's Uzi and hold the mouse button down
3. While holding the click, move the cursor over agent 2's Minigun, then press the other button

Result: Agent 1 drops a Minigun, even if he doesn't have one.

**Comment by mefistotelis** [comment]
Oh wow... how come I never noticed it?
I remember reading comments under that video, but it looks like misunderstood the procedure.

**Comment by mefistotelis** [comment]
Should be fixed with:
[swars: Check which panel initiated a weapon drop before allowing it](https://github.com/swfans/swars/commit/30503e314571d6d7a742e347334b601a127e49a2)

I fixed it on interface side only - so a hacked client (with this change reverted) would still allow this to pass in multiplayer. But we will worry for multiplayer later.

**Comment by geist22** [comment]
Yeah... agent 1 could still drop weapon duplicates, though agent 2-4 couldn't do it anymore.

**Comment by geist22** [comment]
Looks good.
